### PR TITLE
Fix Search Result Emits Twice

### LINKED ISSUE #78: When search for something "search results stream" emit 2 times consecutive the same data
Hi, i played with code and observed that "handleResults" method in SearchFragment is executed 2 times consecutive when searching. It means that "search results stream" in data model emit data 2 times. Is it normal? This issue make difficult adding additional functionality regarding that stream.

Thanks!

### PR DESCRIPTION
**Pull request by peter-tackage**
Resolves #78

### CODE REVIEW

File: app/src/main/java/com/futurice/freesound/feature/search/SearchActivityViewModel.java [hunk 1]
```diff
@@ -34,44 +31,37 @@
...
     private final Analytics analytics;
 
     @NonNull
     private final Subject<String> searchTermOnceAndStream = BehaviorSubject
             .createDefault(NO_SEARCH);
 
-    SearchViewModel(@NonNull final SearchDataModel searchDataModel,
-                    @NonNull final Navigator navigator,
-                    @NonNull final Analytics analytics) {
+    SearchActivityViewModel(@NonNull final SearchDataModel searchDataModel,
```
Comment (tomaszpolanski) [inline app/src/main/java/com/futurice/freesound/feature/search/SearchActivityViewModel.java]: Why not just `@Inject`?

File: app/src/main/java/com/futurice/freesound/feature/search/SearchFragmentViewModel.java [hunk 2]
```diff
@@ -0,0 +1,72 @@
...
+
+final class SearchFragmentViewModel extends BaseViewModel {
+
+    @NonNull
+    private final SearchDataModel searchDataModel;
+
+    @NonNull
+    private final Navigator navigator;
+
+    SearchFragmentViewModel(@NonNull final SearchDataModel searchDataModel,
```
Comment (tomaszpolanski) [inline app/src/main/java/com/futurice/freesound/feature/search/SearchFragmentViewModel.java]: Add `@Inject`?

Comment (peter-tackage) [inline app/src/main/java/com/futurice/freesound/feature/search/SearchFragmentViewModel.java]: Out of consistency, I tend not to use `@Inject`. It's personally preference, but I like being able to visit the module class to see all the dependencies and their scoping in the one place.
